/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUsersRouteImport } from './routes/_auth/users'
import { Route as AuthSinistresRouteImport } from './routes/_auth/sinistres'
import { Route as AuthRolesRouteImport } from './routes/_auth/roles'
import { Route as AuthProductsRouteImport } from './routes/_auth/products'
import { Route as AuthPermissionsRouteImport } from './routes/_auth/permissions'
import { Route as AuthPartnersRouteImport } from './routes/_auth/partners'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthClientsRouteImport } from './routes/_auth/clients'
import { Route as AuthProductsGrilleTarifaireRouteImport } from './routes/_auth/products_.grille-tarifaire'
import { Route as AuthProductsCategoriesRouteImport } from './routes/_auth/products_.categories'
import { Route as AuthProductsAccessoiresRouteImport } from './routes/_auth/products_.accessoires'
import { Route as AuthProductsProductIdRouteImport } from './routes/_auth/products_.$productId'
import { Route as AuthPartnersPartnerIdRouteImport } from './routes/_auth/partners_.$partnerId'
import { Route as AuthProductsGrilleTarifaireRateTableIdRouteImport } from './routes/_auth/products_.grille-tarifaire_.$rateTableId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSinistresRoute = AuthSinistresRouteImport.update({
  id: '/sinistres',
  path: '/sinistres',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesRoute = AuthRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsRoute = AuthProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPermissionsRoute = AuthPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPartnersRoute = AuthPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientsRoute = AuthClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsGrilleTarifaireRoute =
  AuthProductsGrilleTarifaireRouteImport.update({
    id: '/products_/grille-tarifaire',
    path: '/products/grille-tarifaire',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProductsCategoriesRoute = AuthProductsCategoriesRouteImport.update({
  id: '/products_/categories',
  path: '/products/categories',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsAccessoiresRoute = AuthProductsAccessoiresRouteImport.update({
  id: '/products_/accessoires',
  path: '/products/accessoires',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsProductIdRoute = AuthProductsProductIdRouteImport.update({
  id: '/products_/$productId',
  path: '/products/$productId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPartnersPartnerIdRoute = AuthPartnersPartnerIdRouteImport.update({
  id: '/partners_/$partnerId',
  path: '/partners/$partnerId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsGrilleTarifaireRateTableIdRoute =
  AuthProductsGrilleTarifaireRateTableIdRouteImport.update({
    id: '/products_/grille-tarifaire_/$rateTableId',
    path: '/products/grille-tarifaire/$rateTableId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/clients': typeof AuthClientsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/partners': typeof AuthPartnersRoute
  '/permissions': typeof AuthPermissionsRoute
  '/products': typeof AuthProductsRoute
  '/roles': typeof AuthRolesRoute
  '/sinistres': typeof AuthSinistresRoute
  '/users': typeof AuthUsersRoute
  '/partners/$partnerId': typeof AuthPartnersPartnerIdRoute
  '/products/$productId': typeof AuthProductsProductIdRoute
  '/products/accessoires': typeof AuthProductsAccessoiresRoute
  '/products/categories': typeof AuthProductsCategoriesRoute
  '/products/grille-tarifaire': typeof AuthProductsGrilleTarifaireRoute
  '/products/grille-tarifaire/$rateTableId': typeof AuthProductsGrilleTarifaireRateTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/clients': typeof AuthClientsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/partners': typeof AuthPartnersRoute
  '/permissions': typeof AuthPermissionsRoute
  '/products': typeof AuthProductsRoute
  '/roles': typeof AuthRolesRoute
  '/sinistres': typeof AuthSinistresRoute
  '/users': typeof AuthUsersRoute
  '/partners/$partnerId': typeof AuthPartnersPartnerIdRoute
  '/products/$productId': typeof AuthProductsProductIdRoute
  '/products/accessoires': typeof AuthProductsAccessoiresRoute
  '/products/categories': typeof AuthProductsCategoriesRoute
  '/products/grille-tarifaire': typeof AuthProductsGrilleTarifaireRoute
  '/products/grille-tarifaire/$rateTableId': typeof AuthProductsGrilleTarifaireRateTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_auth/clients': typeof AuthClientsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/partners': typeof AuthPartnersRoute
  '/_auth/permissions': typeof AuthPermissionsRoute
  '/_auth/products': typeof AuthProductsRoute
  '/_auth/roles': typeof AuthRolesRoute
  '/_auth/sinistres': typeof AuthSinistresRoute
  '/_auth/users': typeof AuthUsersRoute
  '/_auth/partners_/$partnerId': typeof AuthPartnersPartnerIdRoute
  '/_auth/products_/$productId': typeof AuthProductsProductIdRoute
  '/_auth/products_/accessoires': typeof AuthProductsAccessoiresRoute
  '/_auth/products_/categories': typeof AuthProductsCategoriesRoute
  '/_auth/products_/grille-tarifaire': typeof AuthProductsGrilleTarifaireRoute
  '/_auth/products_/grille-tarifaire_/$rateTableId': typeof AuthProductsGrilleTarifaireRateTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/clients'
    | '/dashboard'
    | '/partners'
    | '/permissions'
    | '/products'
    | '/roles'
    | '/sinistres'
    | '/users'
    | '/partners/$partnerId'
    | '/products/$productId'
    | '/products/accessoires'
    | '/products/categories'
    | '/products/grille-tarifaire'
    | '/products/grille-tarifaire/$rateTableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/clients'
    | '/dashboard'
    | '/partners'
    | '/permissions'
    | '/products'
    | '/roles'
    | '/sinistres'
    | '/users'
    | '/partners/$partnerId'
    | '/products/$productId'
    | '/products/accessoires'
    | '/products/categories'
    | '/products/grille-tarifaire'
    | '/products/grille-tarifaire/$rateTableId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/login'
    | '/_auth/clients'
    | '/_auth/dashboard'
    | '/_auth/partners'
    | '/_auth/permissions'
    | '/_auth/products'
    | '/_auth/roles'
    | '/_auth/sinistres'
    | '/_auth/users'
    | '/_auth/partners_/$partnerId'
    | '/_auth/products_/$productId'
    | '/_auth/products_/accessoires'
    | '/_auth/products_/categories'
    | '/_auth/products_/grille-tarifaire'
    | '/_auth/products_/grille-tarifaire_/$rateTableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sinistres': {
      id: '/_auth/sinistres'
      path: '/sinistres'
      fullPath: '/sinistres'
      preLoaderRoute: typeof AuthSinistresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles': {
      id: '/_auth/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthRolesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products': {
      id: '/_auth/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthProductsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/permissions': {
      id: '/_auth/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthPermissionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/partners': {
      id: '/_auth/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthPartnersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clients': {
      id: '/_auth/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthClientsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products_/grille-tarifaire': {
      id: '/_auth/products_/grille-tarifaire'
      path: '/products/grille-tarifaire'
      fullPath: '/products/grille-tarifaire'
      preLoaderRoute: typeof AuthProductsGrilleTarifaireRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products_/categories': {
      id: '/_auth/products_/categories'
      path: '/products/categories'
      fullPath: '/products/categories'
      preLoaderRoute: typeof AuthProductsCategoriesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products_/accessoires': {
      id: '/_auth/products_/accessoires'
      path: '/products/accessoires'
      fullPath: '/products/accessoires'
      preLoaderRoute: typeof AuthProductsAccessoiresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products_/$productId': {
      id: '/_auth/products_/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthProductsProductIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/partners_/$partnerId': {
      id: '/_auth/partners_/$partnerId'
      path: '/partners/$partnerId'
      fullPath: '/partners/$partnerId'
      preLoaderRoute: typeof AuthPartnersPartnerIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products_/grille-tarifaire_/$rateTableId': {
      id: '/_auth/products_/grille-tarifaire_/$rateTableId'
      path: '/products/grille-tarifaire/$rateTableId'
      fullPath: '/products/grille-tarifaire/$rateTableId'
      preLoaderRoute: typeof AuthProductsGrilleTarifaireRateTableIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthClientsRoute: typeof AuthClientsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthPartnersRoute: typeof AuthPartnersRoute
  AuthPermissionsRoute: typeof AuthPermissionsRoute
  AuthProductsRoute: typeof AuthProductsRoute
  AuthRolesRoute: typeof AuthRolesRoute
  AuthSinistresRoute: typeof AuthSinistresRoute
  AuthUsersRoute: typeof AuthUsersRoute
  AuthPartnersPartnerIdRoute: typeof AuthPartnersPartnerIdRoute
  AuthProductsProductIdRoute: typeof AuthProductsProductIdRoute
  AuthProductsAccessoiresRoute: typeof AuthProductsAccessoiresRoute
  AuthProductsCategoriesRoute: typeof AuthProductsCategoriesRoute
  AuthProductsGrilleTarifaireRoute: typeof AuthProductsGrilleTarifaireRoute
  AuthProductsGrilleTarifaireRateTableIdRoute: typeof AuthProductsGrilleTarifaireRateTableIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthClientsRoute: AuthClientsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthPartnersRoute: AuthPartnersRoute,
  AuthPermissionsRoute: AuthPermissionsRoute,
  AuthProductsRoute: AuthProductsRoute,
  AuthRolesRoute: AuthRolesRoute,
  AuthSinistresRoute: AuthSinistresRoute,
  AuthUsersRoute: AuthUsersRoute,
  AuthPartnersPartnerIdRoute: AuthPartnersPartnerIdRoute,
  AuthProductsProductIdRoute: AuthProductsProductIdRoute,
  AuthProductsAccessoiresRoute: AuthProductsAccessoiresRoute,
  AuthProductsCategoriesRoute: AuthProductsCategoriesRoute,
  AuthProductsGrilleTarifaireRoute: AuthProductsGrilleTarifaireRoute,
  AuthProductsGrilleTarifaireRateTableIdRoute:
    AuthProductsGrilleTarifaireRateTableIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
