/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthClientsRouteImport } from './routes/_auth/clients'
import { Route as AuthCotationsRouteImport } from './routes/_auth/cotations'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthPartnersRouteImport } from './routes/_auth/partners'
import { Route as AuthPermissionsRouteImport } from './routes/_auth/permissions'
import { Route as AuthProfilRouteImport } from './routes/_auth/profil'
import { Route as AuthRolesRouteImport } from './routes/_auth/roles'
import { Route as AuthSinistresRouteImport } from './routes/_auth/sinistres'
import { Route as AuthSupportRouteImport } from './routes/_auth/support'
import { Route as AuthUsersRouteImport } from './routes/_auth/users'
import { Route as AuthClientsClientIdRouteImport } from './routes/_auth/clients_.$clientId'
import { Route as AuthCommissionsDistributionsRouteImport } from './routes/_auth/commissions.distributions'
import { Route as AuthCommissionsSchemesRouteImport } from './routes/_auth/commissions.schemes'
import { Route as AuthCommissionsWalletsRouteImport } from './routes/_auth/commissions.wallets'
import { Route as AuthPartnersPartnerIdRouteImport } from './routes/_auth/partners_.$partnerId'
import { Route as AuthProduitsIaIaPourTousRouteImport } from './routes/_auth/produits-ia.ia-pour-tous'
import { Route as AuthProduitsIaIaStandardRouteImport } from './routes/_auth/produits-ia.ia-standard'
import { Route as AuthSinistresClaimIdRouteImport } from './routes/_auth/sinistres_.$claimId'
import { Route as AuthSinistresTypesRouteImport } from './routes/_auth/sinistres_.types'
import { Route as AuthSupportConversationIdRouteImport } from './routes/_auth/support_.$conversationId'
import { Route as AuthCommissionsSchemesNewRouteImport } from './routes/_auth/commissions.schemes_.new'
import { Route as AuthPartnersPartnerIdRelationsRouteImport } from './routes/_auth/partners_.$partnerId_.relations'
import { Route as AuthProduitsIaIaStandardIndexRouteImport } from './routes/_auth/produits-ia.ia-standard.index'
import { Route as AuthProduitsIaIaStandardAccessoiresRouteImport } from './routes/_auth/produits-ia.ia-standard.accessoires'
import { Route as AuthProduitsIaIaStandardBaremesRouteImport } from './routes/_auth/produits-ia.ia-standard.baremes'
import { Route as AuthProduitsIaIaStandardClassesRouteImport } from './routes/_auth/produits-ia.ia-standard.classes'
import { Route as AuthProduitsIaIaStandardMajorationsRouteImport } from './routes/_auth/produits-ia.ia-standard.majorations'
import { Route as AuthProduitsIaIaStandardProrataRouteImport } from './routes/_auth/produits-ia.ia-standard.prorata'
import { Route as AuthProduitsIaIaStandardReglagesRouteImport } from './routes/_auth/produits-ia.ia-standard.reglages'
import { Route as AuthCommissionsSchemesSchemeIdEditRouteImport } from './routes/_auth/commissions.schemes_.$schemeId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthClientsRoute = AuthClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCotationsRoute = AuthCotationsRouteImport.update({
  id: '/cotations',
  path: '/cotations',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPartnersRoute = AuthPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPermissionsRoute = AuthPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfilRoute = AuthProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesRoute = AuthRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSinistresRoute = AuthSinistresRouteImport.update({
  id: '/sinistres',
  path: '/sinistres',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSupportRoute = AuthSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientsClientIdRoute = AuthClientsClientIdRouteImport.update({
  id: '/clients_/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCommissionsDistributionsRoute =
  AuthCommissionsDistributionsRouteImport.update({
    id: '/commissions/distributions',
    path: '/commissions/distributions',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCommissionsSchemesRoute = AuthCommissionsSchemesRouteImport.update({
  id: '/commissions/schemes',
  path: '/commissions/schemes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCommissionsWalletsRoute = AuthCommissionsWalletsRouteImport.update({
  id: '/commissions/wallets',
  path: '/commissions/wallets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPartnersPartnerIdRoute = AuthPartnersPartnerIdRouteImport.update({
  id: '/partners_/$partnerId',
  path: '/partners/$partnerId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProduitsIaIaPourTousRoute =
  AuthProduitsIaIaPourTousRouteImport.update({
    id: '/produits-ia/ia-pour-tous',
    path: '/produits-ia/ia-pour-tous',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProduitsIaIaStandardRoute =
  AuthProduitsIaIaStandardRouteImport.update({
    id: '/produits-ia/ia-standard',
    path: '/produits-ia/ia-standard',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSinistresClaimIdRoute = AuthSinistresClaimIdRouteImport.update({
  id: '/sinistres_/$claimId',
  path: '/sinistres/$claimId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSinistresTypesRoute = AuthSinistresTypesRouteImport.update({
  id: '/sinistres_/types',
  path: '/sinistres/types',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSupportConversationIdRoute =
  AuthSupportConversationIdRouteImport.update({
    id: '/support_/$conversationId',
    path: '/support/$conversationId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCommissionsSchemesNewRoute =
  AuthCommissionsSchemesNewRouteImport.update({
    id: '/commissions/schemes_/new',
    path: '/commissions/schemes/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthPartnersPartnerIdRelationsRoute =
  AuthPartnersPartnerIdRelationsRouteImport.update({
    id: '/partners_/$partnerId_/relations',
    path: '/partners/$partnerId/relations',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProduitsIaIaStandardIndexRoute =
  AuthProduitsIaIaStandardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthProduitsIaIaStandardRoute,
  } as any)
const AuthProduitsIaIaStandardAccessoiresRoute =
  AuthProduitsIaIaStandardAccessoiresRouteImport.update({
    id: '/accessoires',
    path: '/accessoires',
    getParentRoute: () => AuthProduitsIaIaStandardRoute,
  } as any)
const AuthProduitsIaIaStandardBaremesRoute =
  AuthProduitsIaIaStandardBaremesRouteImport.update({
    id: '/baremes',
    path: '/baremes',
    getParentRoute: () => AuthProduitsIaIaStandardRoute,
  } as any)
const AuthProduitsIaIaStandardClassesRoute =
  AuthProduitsIaIaStandardClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthProduitsIaIaStandardRoute,
  } as any)
const AuthProduitsIaIaStandardMajorationsRoute =
  AuthProduitsIaIaStandardMajorationsRouteImport.update({
    id: '/majorations',
    path: '/majorations',
    getParentRoute: () => AuthProduitsIaIaStandardRoute,
  } as any)
const AuthProduitsIaIaStandardProrataRoute =
  AuthProduitsIaIaStandardProrataRouteImport.update({
    id: '/prorata',
    path: '/prorata',
    getParentRoute: () => AuthProduitsIaIaStandardRoute,
  } as any)
const AuthProduitsIaIaStandardReglagesRoute =
  AuthProduitsIaIaStandardReglagesRouteImport.update({
    id: '/reglages',
    path: '/reglages',
    getParentRoute: () => AuthProduitsIaIaStandardRoute,
  } as any)
const AuthCommissionsSchemesSchemeIdEditRoute =
  AuthCommissionsSchemesSchemeIdEditRouteImport.update({
    id: '/commissions/schemes_/$schemeId/edit',
    path: '/commissions/schemes/$schemeId/edit',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clients': typeof AuthClientsRoute
  '/cotations': typeof AuthCotationsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/partners': typeof AuthPartnersRoute
  '/permissions': typeof AuthPermissionsRoute
  '/profil': typeof AuthProfilRoute
  '/roles': typeof AuthRolesRoute
  '/sinistres': typeof AuthSinistresRoute
  '/support': typeof AuthSupportRoute
  '/users': typeof AuthUsersRoute
  '/clients/$clientId': typeof AuthClientsClientIdRoute
  '/commissions/distributions': typeof AuthCommissionsDistributionsRoute
  '/commissions/schemes': typeof AuthCommissionsSchemesRoute
  '/commissions/wallets': typeof AuthCommissionsWalletsRoute
  '/partners/$partnerId': typeof AuthPartnersPartnerIdRoute
  '/produits-ia/ia-pour-tous': typeof AuthProduitsIaIaPourTousRoute
  '/produits-ia/ia-standard': typeof AuthProduitsIaIaStandardRouteWithChildren
  '/sinistres/$claimId': typeof AuthSinistresClaimIdRoute
  '/sinistres/types': typeof AuthSinistresTypesRoute
  '/support/$conversationId': typeof AuthSupportConversationIdRoute
  '/commissions/schemes/new': typeof AuthCommissionsSchemesNewRoute
  '/partners/$partnerId/relations': typeof AuthPartnersPartnerIdRelationsRoute
  '/produits-ia/ia-standard/accessoires': typeof AuthProduitsIaIaStandardAccessoiresRoute
  '/produits-ia/ia-standard/baremes': typeof AuthProduitsIaIaStandardBaremesRoute
  '/produits-ia/ia-standard/classes': typeof AuthProduitsIaIaStandardClassesRoute
  '/produits-ia/ia-standard/majorations': typeof AuthProduitsIaIaStandardMajorationsRoute
  '/produits-ia/ia-standard/prorata': typeof AuthProduitsIaIaStandardProrataRoute
  '/produits-ia/ia-standard/reglages': typeof AuthProduitsIaIaStandardReglagesRoute
  '/produits-ia/ia-standard/': typeof AuthProduitsIaIaStandardIndexRoute
  '/commissions/schemes/$schemeId/edit': typeof AuthCommissionsSchemesSchemeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clients': typeof AuthClientsRoute
  '/cotations': typeof AuthCotationsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/partners': typeof AuthPartnersRoute
  '/permissions': typeof AuthPermissionsRoute
  '/profil': typeof AuthProfilRoute
  '/roles': typeof AuthRolesRoute
  '/sinistres': typeof AuthSinistresRoute
  '/support': typeof AuthSupportRoute
  '/users': typeof AuthUsersRoute
  '/clients/$clientId': typeof AuthClientsClientIdRoute
  '/commissions/distributions': typeof AuthCommissionsDistributionsRoute
  '/commissions/schemes': typeof AuthCommissionsSchemesRoute
  '/commissions/wallets': typeof AuthCommissionsWalletsRoute
  '/partners/$partnerId': typeof AuthPartnersPartnerIdRoute
  '/produits-ia/ia-pour-tous': typeof AuthProduitsIaIaPourTousRoute
  '/sinistres/$claimId': typeof AuthSinistresClaimIdRoute
  '/sinistres/types': typeof AuthSinistresTypesRoute
  '/support/$conversationId': typeof AuthSupportConversationIdRoute
  '/commissions/schemes/new': typeof AuthCommissionsSchemesNewRoute
  '/partners/$partnerId/relations': typeof AuthPartnersPartnerIdRelationsRoute
  '/produits-ia/ia-standard/accessoires': typeof AuthProduitsIaIaStandardAccessoiresRoute
  '/produits-ia/ia-standard/baremes': typeof AuthProduitsIaIaStandardBaremesRoute
  '/produits-ia/ia-standard/classes': typeof AuthProduitsIaIaStandardClassesRoute
  '/produits-ia/ia-standard/majorations': typeof AuthProduitsIaIaStandardMajorationsRoute
  '/produits-ia/ia-standard/prorata': typeof AuthProduitsIaIaStandardProrataRoute
  '/produits-ia/ia-standard/reglages': typeof AuthProduitsIaIaStandardReglagesRoute
  '/produits-ia/ia-standard': typeof AuthProduitsIaIaStandardIndexRoute
  '/commissions/schemes/$schemeId/edit': typeof AuthCommissionsSchemesSchemeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_auth/clients': typeof AuthClientsRoute
  '/_auth/cotations': typeof AuthCotationsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/partners': typeof AuthPartnersRoute
  '/_auth/permissions': typeof AuthPermissionsRoute
  '/_auth/profil': typeof AuthProfilRoute
  '/_auth/roles': typeof AuthRolesRoute
  '/_auth/sinistres': typeof AuthSinistresRoute
  '/_auth/support': typeof AuthSupportRoute
  '/_auth/users': typeof AuthUsersRoute
  '/_auth/clients_/$clientId': typeof AuthClientsClientIdRoute
  '/_auth/commissions/distributions': typeof AuthCommissionsDistributionsRoute
  '/_auth/commissions/schemes': typeof AuthCommissionsSchemesRoute
  '/_auth/commissions/wallets': typeof AuthCommissionsWalletsRoute
  '/_auth/partners_/$partnerId': typeof AuthPartnersPartnerIdRoute
  '/_auth/produits-ia/ia-pour-tous': typeof AuthProduitsIaIaPourTousRoute
  '/_auth/produits-ia/ia-standard': typeof AuthProduitsIaIaStandardRouteWithChildren
  '/_auth/sinistres_/$claimId': typeof AuthSinistresClaimIdRoute
  '/_auth/sinistres_/types': typeof AuthSinistresTypesRoute
  '/_auth/support_/$conversationId': typeof AuthSupportConversationIdRoute
  '/_auth/commissions/schemes_/new': typeof AuthCommissionsSchemesNewRoute
  '/_auth/partners_/$partnerId_/relations': typeof AuthPartnersPartnerIdRelationsRoute
  '/_auth/produits-ia/ia-standard/accessoires': typeof AuthProduitsIaIaStandardAccessoiresRoute
  '/_auth/produits-ia/ia-standard/baremes': typeof AuthProduitsIaIaStandardBaremesRoute
  '/_auth/produits-ia/ia-standard/classes': typeof AuthProduitsIaIaStandardClassesRoute
  '/_auth/produits-ia/ia-standard/majorations': typeof AuthProduitsIaIaStandardMajorationsRoute
  '/_auth/produits-ia/ia-standard/prorata': typeof AuthProduitsIaIaStandardProrataRoute
  '/_auth/produits-ia/ia-standard/reglages': typeof AuthProduitsIaIaStandardReglagesRoute
  '/_auth/produits-ia/ia-standard/': typeof AuthProduitsIaIaStandardIndexRoute
  '/_auth/commissions/schemes_/$schemeId/edit': typeof AuthCommissionsSchemesSchemeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/clients'
    | '/cotations'
    | '/dashboard'
    | '/partners'
    | '/permissions'
    | '/profil'
    | '/roles'
    | '/sinistres'
    | '/support'
    | '/users'
    | '/clients/$clientId'
    | '/commissions/distributions'
    | '/commissions/schemes'
    | '/commissions/wallets'
    | '/partners/$partnerId'
    | '/produits-ia/ia-pour-tous'
    | '/produits-ia/ia-standard'
    | '/sinistres/$claimId'
    | '/sinistres/types'
    | '/support/$conversationId'
    | '/commissions/schemes/new'
    | '/partners/$partnerId/relations'
    | '/produits-ia/ia-standard/accessoires'
    | '/produits-ia/ia-standard/baremes'
    | '/produits-ia/ia-standard/classes'
    | '/produits-ia/ia-standard/majorations'
    | '/produits-ia/ia-standard/prorata'
    | '/produits-ia/ia-standard/reglages'
    | '/produits-ia/ia-standard/'
    | '/commissions/schemes/$schemeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/clients'
    | '/cotations'
    | '/dashboard'
    | '/partners'
    | '/permissions'
    | '/profil'
    | '/roles'
    | '/sinistres'
    | '/support'
    | '/users'
    | '/clients/$clientId'
    | '/commissions/distributions'
    | '/commissions/schemes'
    | '/commissions/wallets'
    | '/partners/$partnerId'
    | '/produits-ia/ia-pour-tous'
    | '/sinistres/$claimId'
    | '/sinistres/types'
    | '/support/$conversationId'
    | '/commissions/schemes/new'
    | '/partners/$partnerId/relations'
    | '/produits-ia/ia-standard/accessoires'
    | '/produits-ia/ia-standard/baremes'
    | '/produits-ia/ia-standard/classes'
    | '/produits-ia/ia-standard/majorations'
    | '/produits-ia/ia-standard/prorata'
    | '/produits-ia/ia-standard/reglages'
    | '/produits-ia/ia-standard'
    | '/commissions/schemes/$schemeId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_auth/clients'
    | '/_auth/cotations'
    | '/_auth/dashboard'
    | '/_auth/partners'
    | '/_auth/permissions'
    | '/_auth/profil'
    | '/_auth/roles'
    | '/_auth/sinistres'
    | '/_auth/support'
    | '/_auth/users'
    | '/_auth/clients_/$clientId'
    | '/_auth/commissions/distributions'
    | '/_auth/commissions/schemes'
    | '/_auth/commissions/wallets'
    | '/_auth/partners_/$partnerId'
    | '/_auth/produits-ia/ia-pour-tous'
    | '/_auth/produits-ia/ia-standard'
    | '/_auth/sinistres_/$claimId'
    | '/_auth/sinistres_/types'
    | '/_auth/support_/$conversationId'
    | '/_auth/commissions/schemes_/new'
    | '/_auth/partners_/$partnerId_/relations'
    | '/_auth/produits-ia/ia-standard/accessoires'
    | '/_auth/produits-ia/ia-standard/baremes'
    | '/_auth/produits-ia/ia-standard/classes'
    | '/_auth/produits-ia/ia-standard/majorations'
    | '/_auth/produits-ia/ia-standard/prorata'
    | '/_auth/produits-ia/ia-standard/reglages'
    | '/_auth/produits-ia/ia-standard/'
    | '/_auth/commissions/schemes_/$schemeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/clients': {
      id: '/_auth/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthClientsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cotations': {
      id: '/_auth/cotations'
      path: '/cotations'
      fullPath: '/cotations'
      preLoaderRoute: typeof AuthCotationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/partners': {
      id: '/_auth/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthPartnersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/permissions': {
      id: '/_auth/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthPermissionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profil': {
      id: '/_auth/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthProfilRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles': {
      id: '/_auth/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthRolesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sinistres': {
      id: '/_auth/sinistres'
      path: '/sinistres'
      fullPath: '/sinistres'
      preLoaderRoute: typeof AuthSinistresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/support': {
      id: '/_auth/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthSupportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clients_/$clientId': {
      id: '/_auth/clients_/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthClientsClientIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commissions/distributions': {
      id: '/_auth/commissions/distributions'
      path: '/commissions/distributions'
      fullPath: '/commissions/distributions'
      preLoaderRoute: typeof AuthCommissionsDistributionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commissions/schemes': {
      id: '/_auth/commissions/schemes'
      path: '/commissions/schemes'
      fullPath: '/commissions/schemes'
      preLoaderRoute: typeof AuthCommissionsSchemesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commissions/wallets': {
      id: '/_auth/commissions/wallets'
      path: '/commissions/wallets'
      fullPath: '/commissions/wallets'
      preLoaderRoute: typeof AuthCommissionsWalletsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/partners_/$partnerId': {
      id: '/_auth/partners_/$partnerId'
      path: '/partners/$partnerId'
      fullPath: '/partners/$partnerId'
      preLoaderRoute: typeof AuthPartnersPartnerIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/produits-ia/ia-pour-tous': {
      id: '/_auth/produits-ia/ia-pour-tous'
      path: '/produits-ia/ia-pour-tous'
      fullPath: '/produits-ia/ia-pour-tous'
      preLoaderRoute: typeof AuthProduitsIaIaPourTousRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/produits-ia/ia-standard': {
      id: '/_auth/produits-ia/ia-standard'
      path: '/produits-ia/ia-standard'
      fullPath: '/produits-ia/ia-standard'
      preLoaderRoute: typeof AuthProduitsIaIaStandardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sinistres_/$claimId': {
      id: '/_auth/sinistres_/$claimId'
      path: '/sinistres/$claimId'
      fullPath: '/sinistres/$claimId'
      preLoaderRoute: typeof AuthSinistresClaimIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sinistres_/types': {
      id: '/_auth/sinistres_/types'
      path: '/sinistres/types'
      fullPath: '/sinistres/types'
      preLoaderRoute: typeof AuthSinistresTypesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/support_/$conversationId': {
      id: '/_auth/support_/$conversationId'
      path: '/support/$conversationId'
      fullPath: '/support/$conversationId'
      preLoaderRoute: typeof AuthSupportConversationIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commissions/schemes_/new': {
      id: '/_auth/commissions/schemes_/new'
      path: '/commissions/schemes/new'
      fullPath: '/commissions/schemes/new'
      preLoaderRoute: typeof AuthCommissionsSchemesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/partners_/$partnerId_/relations': {
      id: '/_auth/partners_/$partnerId_/relations'
      path: '/partners/$partnerId/relations'
      fullPath: '/partners/$partnerId/relations'
      preLoaderRoute: typeof AuthPartnersPartnerIdRelationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/produits-ia/ia-standard/': {
      id: '/_auth/produits-ia/ia-standard/'
      path: '/'
      fullPath: '/produits-ia/ia-standard/'
      preLoaderRoute: typeof AuthProduitsIaIaStandardIndexRouteImport
      parentRoute: typeof AuthProduitsIaIaStandardRoute
    }
    '/_auth/produits-ia/ia-standard/accessoires': {
      id: '/_auth/produits-ia/ia-standard/accessoires'
      path: '/accessoires'
      fullPath: '/produits-ia/ia-standard/accessoires'
      preLoaderRoute: typeof AuthProduitsIaIaStandardAccessoiresRouteImport
      parentRoute: typeof AuthProduitsIaIaStandardRoute
    }
    '/_auth/produits-ia/ia-standard/baremes': {
      id: '/_auth/produits-ia/ia-standard/baremes'
      path: '/baremes'
      fullPath: '/produits-ia/ia-standard/baremes'
      preLoaderRoute: typeof AuthProduitsIaIaStandardBaremesRouteImport
      parentRoute: typeof AuthProduitsIaIaStandardRoute
    }
    '/_auth/produits-ia/ia-standard/classes': {
      id: '/_auth/produits-ia/ia-standard/classes'
      path: '/classes'
      fullPath: '/produits-ia/ia-standard/classes'
      preLoaderRoute: typeof AuthProduitsIaIaStandardClassesRouteImport
      parentRoute: typeof AuthProduitsIaIaStandardRoute
    }
    '/_auth/produits-ia/ia-standard/majorations': {
      id: '/_auth/produits-ia/ia-standard/majorations'
      path: '/majorations'
      fullPath: '/produits-ia/ia-standard/majorations'
      preLoaderRoute: typeof AuthProduitsIaIaStandardMajorationsRouteImport
      parentRoute: typeof AuthProduitsIaIaStandardRoute
    }
    '/_auth/produits-ia/ia-standard/prorata': {
      id: '/_auth/produits-ia/ia-standard/prorata'
      path: '/prorata'
      fullPath: '/produits-ia/ia-standard/prorata'
      preLoaderRoute: typeof AuthProduitsIaIaStandardProrataRouteImport
      parentRoute: typeof AuthProduitsIaIaStandardRoute
    }
    '/_auth/produits-ia/ia-standard/reglages': {
      id: '/_auth/produits-ia/ia-standard/reglages'
      path: '/reglages'
      fullPath: '/produits-ia/ia-standard/reglages'
      preLoaderRoute: typeof AuthProduitsIaIaStandardReglagesRouteImport
      parentRoute: typeof AuthProduitsIaIaStandardRoute
    }
    '/_auth/commissions/schemes_/$schemeId/edit': {
      id: '/_auth/commissions/schemes_/$schemeId/edit'
      path: '/commissions/schemes/$schemeId/edit'
      fullPath: '/commissions/schemes/$schemeId/edit'
      preLoaderRoute: typeof AuthCommissionsSchemesSchemeIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthProduitsIaIaStandardRouteChildren {
  AuthProduitsIaIaStandardAccessoiresRoute: typeof AuthProduitsIaIaStandardAccessoiresRoute
  AuthProduitsIaIaStandardBaremesRoute: typeof AuthProduitsIaIaStandardBaremesRoute
  AuthProduitsIaIaStandardClassesRoute: typeof AuthProduitsIaIaStandardClassesRoute
  AuthProduitsIaIaStandardMajorationsRoute: typeof AuthProduitsIaIaStandardMajorationsRoute
  AuthProduitsIaIaStandardProrataRoute: typeof AuthProduitsIaIaStandardProrataRoute
  AuthProduitsIaIaStandardReglagesRoute: typeof AuthProduitsIaIaStandardReglagesRoute
  AuthProduitsIaIaStandardIndexRoute: typeof AuthProduitsIaIaStandardIndexRoute
}

const AuthProduitsIaIaStandardRouteChildren: AuthProduitsIaIaStandardRouteChildren =
  {
    AuthProduitsIaIaStandardAccessoiresRoute:
      AuthProduitsIaIaStandardAccessoiresRoute,
    AuthProduitsIaIaStandardBaremesRoute: AuthProduitsIaIaStandardBaremesRoute,
    AuthProduitsIaIaStandardClassesRoute: AuthProduitsIaIaStandardClassesRoute,
    AuthProduitsIaIaStandardMajorationsRoute:
      AuthProduitsIaIaStandardMajorationsRoute,
    AuthProduitsIaIaStandardProrataRoute: AuthProduitsIaIaStandardProrataRoute,
    AuthProduitsIaIaStandardReglagesRoute:
      AuthProduitsIaIaStandardReglagesRoute,
    AuthProduitsIaIaStandardIndexRoute: AuthProduitsIaIaStandardIndexRoute,
  }

const AuthProduitsIaIaStandardRouteWithChildren =
  AuthProduitsIaIaStandardRoute._addFileChildren(
    AuthProduitsIaIaStandardRouteChildren,
  )

interface AuthRouteChildren {
  AuthClientsRoute: typeof AuthClientsRoute
  AuthCotationsRoute: typeof AuthCotationsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthPartnersRoute: typeof AuthPartnersRoute
  AuthPermissionsRoute: typeof AuthPermissionsRoute
  AuthProfilRoute: typeof AuthProfilRoute
  AuthRolesRoute: typeof AuthRolesRoute
  AuthSinistresRoute: typeof AuthSinistresRoute
  AuthSupportRoute: typeof AuthSupportRoute
  AuthUsersRoute: typeof AuthUsersRoute
  AuthClientsClientIdRoute: typeof AuthClientsClientIdRoute
  AuthCommissionsDistributionsRoute: typeof AuthCommissionsDistributionsRoute
  AuthCommissionsSchemesRoute: typeof AuthCommissionsSchemesRoute
  AuthCommissionsWalletsRoute: typeof AuthCommissionsWalletsRoute
  AuthPartnersPartnerIdRoute: typeof AuthPartnersPartnerIdRoute
  AuthProduitsIaIaPourTousRoute: typeof AuthProduitsIaIaPourTousRoute
  AuthProduitsIaIaStandardRoute: typeof AuthProduitsIaIaStandardRouteWithChildren
  AuthSinistresClaimIdRoute: typeof AuthSinistresClaimIdRoute
  AuthSinistresTypesRoute: typeof AuthSinistresTypesRoute
  AuthSupportConversationIdRoute: typeof AuthSupportConversationIdRoute
  AuthCommissionsSchemesNewRoute: typeof AuthCommissionsSchemesNewRoute
  AuthPartnersPartnerIdRelationsRoute: typeof AuthPartnersPartnerIdRelationsRoute
  AuthCommissionsSchemesSchemeIdEditRoute: typeof AuthCommissionsSchemesSchemeIdEditRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthClientsRoute: AuthClientsRoute,
  AuthCotationsRoute: AuthCotationsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthPartnersRoute: AuthPartnersRoute,
  AuthPermissionsRoute: AuthPermissionsRoute,
  AuthProfilRoute: AuthProfilRoute,
  AuthRolesRoute: AuthRolesRoute,
  AuthSinistresRoute: AuthSinistresRoute,
  AuthSupportRoute: AuthSupportRoute,
  AuthUsersRoute: AuthUsersRoute,
  AuthClientsClientIdRoute: AuthClientsClientIdRoute,
  AuthCommissionsDistributionsRoute: AuthCommissionsDistributionsRoute,
  AuthCommissionsSchemesRoute: AuthCommissionsSchemesRoute,
  AuthCommissionsWalletsRoute: AuthCommissionsWalletsRoute,
  AuthPartnersPartnerIdRoute: AuthPartnersPartnerIdRoute,
  AuthProduitsIaIaPourTousRoute: AuthProduitsIaIaPourTousRoute,
  AuthProduitsIaIaStandardRoute: AuthProduitsIaIaStandardRouteWithChildren,
  AuthSinistresClaimIdRoute: AuthSinistresClaimIdRoute,
  AuthSinistresTypesRoute: AuthSinistresTypesRoute,
  AuthSupportConversationIdRoute: AuthSupportConversationIdRoute,
  AuthCommissionsSchemesNewRoute: AuthCommissionsSchemesNewRoute,
  AuthPartnersPartnerIdRelationsRoute: AuthPartnersPartnerIdRelationsRoute,
  AuthCommissionsSchemesSchemeIdEditRoute:
    AuthCommissionsSchemesSchemeIdEditRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
